package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Thursday, September 17, 2026 8:15:12 PM UTC
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
